[project]
name = "gitlab-env"
version = "0.2.0"
description = "Tool to get/set variables for given Gitlab project"
authors = [
    { name = "Eugene Aryapov", email = "e.aryapov@oom.ag" },
    { name = "Stan Bogatkin", email = "s@sbog.ru" }
]
readme = "README.md"
dependencies = [
    "python-gitlab ==3.15.0",
    "GitPython ==3.1.35"
]
requires-python = ">=3.8"

packages = [{include = "gitlab_env"}]

[project.scripts]
gitlab-env = "gitlab_env.gitlab_ci_env:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
